import argparse
import json
import os
import sys
import time
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from builtin.processor.engine import (
    DEFAULT_NORMALIZERS_ROOT,
    ProcessorEngine,
    apply_predict_config_overrides,
    default_collectors_root,
    env_float,
    iter_collector_jsonl_files,
    utc_timestamp,
    write_json_atomic,
)


DEFAULT_DEBUG_STATE_DIR = REPO_ROOT / "debug" / "work" / "processors" / "predict_debug"


def mark_existing_collector_files_seen(engine):
    engine.checkpoint = {"version": 1, "files": {}, "updated_at": utc_timestamp()}
    for path in iter_collector_jsonl_files(engine.collectors_root):
        try:
            size = Path(path).stat().st_size
        except OSError:
            continue
        engine.checkpoint["files"][str(path)] = {
            "offset": size,
            "size": size,
            "updated_at": utc_timestamp(),
        }
    write_json_atomic(engine.checkpoint_path, engine.checkpoint)


def compact_prediction(scan_result, max_patterns):
    prediction = scan_result.get("prediction") or {}
    payload = prediction.get("payload") or {}
    patterns = payload.get("patterns") or []
    return {
        "type": "prediction_generated",
        "created_at": scan_result.get("created_at"),
        "prediction_id": prediction.get("id"),
        "confidence": prediction.get("confidence", 0.0),
        "min_confidence": payload.get("min_confidence", 0.0),
        "normalized_count": scan_result.get("normalized_count", 0),
        "events_processed": payload.get("events_processed", 0),
        "transactions_seen": payload.get("transactions_seen", 0),
        "min_transactions_before_prediction": payload.get(
            "min_transactions_before_prediction",
            0,
        ),
        "min_pattern_decayed_count": payload.get("min_pattern_decayed_count", 0.0),
        "min_support": payload.get("min_support", 0.0),
        "dictionary_size": payload.get("dictionary_size", 0),
        "effective_transaction_count": payload.get("effective_transaction_count", 0),
        "patterns": patterns[:max_patterns],
        "normalized_log_path": scan_result.get("normalized_log_path"),
        "last_result_path": scan_result.get("last_result_path"),
        "errors": scan_result.get("errors") or [],
    }


def print_prediction(scan_result, args):
    output = scan_result["prediction"] if args.full else compact_prediction(
        scan_result,
        args.max_patterns,
    )
    if args.jsonl:
        print(json.dumps(output, ensure_ascii=True, sort_keys=True), flush=True)
        return
    print(json.dumps(output, ensure_ascii=True, indent=2, sort_keys=True), flush=True)


def run(args):
    apply_predict_config_overrides(args)
    engine = ProcessorEngine(
        collectors_root=args.collectors_root,
        normalizers_root=args.normalizers_root,
        state_dir=args.state_dir,
        predict_state_dir=args.predict_state_dir,
    )

    if args.replay_existing:
        engine.reset()
    elif args.reset or not engine.checkpoint_path.exists():
        mark_existing_collector_files_seen(engine)

    if args.print_started:
        print(
            json.dumps(
                {
                    "type": "debug_started",
                    "collectors_root": str(engine.collectors_root),
                    "normalizers_root": str(engine.normalizers_root),
                    "state_dir": str(engine.state_dir),
                    "mode": "replay_existing" if args.replay_existing else "tail",
                },
                ensure_ascii=True,
                sort_keys=True,
            ),
            flush=True,
        )

    deadline = None if args.duration <= 0 else time.monotonic() + args.duration
    while True:
        scan_result = engine.scan_once()
        if scan_result.get("prediction"):
            print_prediction(scan_result, args)
        elif args.print_empty:
            print(
                json.dumps(
                    {
                        "type": "no_prediction",
                        "created_at": scan_result.get("created_at"),
                        "files_seen": scan_result.get("files_seen", 0),
                        "events_seen": scan_result.get("events_seen", 0),
                        "learning": scan_result.get("learning") or {},
                        "errors": scan_result.get("errors") or [],
                    },
                    ensure_ascii=True,
                    sort_keys=True,
                ),
                flush=True,
            )

        if args.once:
            return
        if deadline is not None and time.monotonic() >= deadline:
            return
        time.sleep(max(args.interval, 0.1))


def parse_args():
    parser = argparse.ArgumentParser(
        description="Print each new prediction generated by the processor engine."
    )
    parser.add_argument(
        "--collectors-root",
        default=os.environ.get("RADAR_COLLECTORS_ROOT", str(default_collectors_root())),
        help="Root containing collector work directories.",
    )
    parser.add_argument(
        "--normalizers-root",
        default=os.environ.get("RADAR_NORMALIZERS_ROOT", str(DEFAULT_NORMALIZERS_ROOT)),
        help="Root containing collector-id normalizer directories.",
    )
    parser.add_argument(
        "--state-dir",
        default=os.environ.get("RADAR_DEBUG_PROCESSOR_STATE_DIR", str(DEFAULT_DEBUG_STATE_DIR)),
        help="Debug checkpoint and normalized output directory.",
    )
    parser.add_argument(
        "--predict-state-dir",
        default=os.environ.get("RADAR_DEBUG_PREDICT_STATE_DIR"),
        help="Optional predict model state directory. Defaults under debug state.",
    )
    parser.add_argument(
        "--interval",
        type=float,
        default=env_float("RADAR_DEBUG_PROCESSOR_INTERVAL", 1),
        help="Seconds between collector scans.",
    )
    parser.add_argument(
        "--duration",
        type=float,
        default=env_float("RADAR_DEBUG_PROCESSOR_DURATION", 0),
        help="Seconds to run. Use <= 0 to run until interrupted.",
    )
    parser.add_argument(
        "--max-patterns",
        type=int,
        default=10,
        help="Maximum patterns to print in compact mode.",
    )
    parser.add_argument(
        "--once",
        action="store_true",
        help="Scan once and exit.",
    )
    parser.add_argument(
        "--reset",
        action="store_true",
        help="Reset debug offsets, then tail from the current end of existing collector files.",
    )
    parser.add_argument(
        "--replay-existing",
        action="store_true",
        help="Process existing collector records instead of tailing only new records.",
    )
    parser.add_argument(
        "--print-empty",
        action="store_true",
        help="Print scan ticks even when no prediction is generated.",
    )
    parser.add_argument(
        "--print-started",
        action="store_true",
        help="Print a startup event before watching.",
    )
    parser.add_argument(
        "--jsonl",
        action="store_true",
        help="Print each event on one line.",
    )
    parser.add_argument(
        "--full",
        action="store_true",
        help="Print the full prediction result instead of a compact debug event.",
    )
    parser.add_argument(
        "--min-transactions-before-prediction",
        type=int,
        help="Minimum total learned transactions required before predictions are emitted.",
    )
    parser.add_argument(
        "--min-confidence",
        type=float,
        help="Minimum top-pattern confidence required before predictions are emitted.",
    )
    parser.add_argument(
        "--min-pattern-decayed-count",
        type=float,
        help="Minimum decayed count required for a pattern to be eligible.",
    )
    return parser.parse_args()


def main():
    run(parse_args())


if __name__ == "__main__":
    main()
